```mermaid

graph TD
    A[API Gateway] --> B[Auth Service]
    A --> C[User Service]
    A --> D[Problem Service]
    A --> E[Judge Service]
    A --> F[Submission Service]
    A --> G[Ranking Service]

    subgraph Message_Broker
        H[RabbitMQ/Kafka]
    end

    B --> B1[(Auth DB)]
    C --> C1[(User DB)]
    D --> D1[(Problem DB)]
    E --> E1[(Judge DB)]
    F --> F1[(Submission DB)]
    G --> G1[(Ranking DB)]

    F --> H
    H --> E
    E --> H
    H --> G

    subgraph Caching
        I[Redis]
    end

    G --> I
    E --> I

    subgraph Code_Execution
        J[Docker Containers]
    end

    E --> J

    ```